version: '3'

services:
  challenge:
    image: dataeater:DiceCTF2022
    build: .
    ports:
      - "31337:31337"
    volumes:
      - ./exploit.py:/home/data-eater/exploit.py